---
title: 'Homework #3'
author: "Nathaniel Haulk"
date: "10/14/2021"
output: pdf_document
---

# Question 1

```{r Q1, echo = TRUE}
set.seed(12) # to be reproducible

## Creates a 50 x 10 matrix with the values 1-500
A = matrix(data = runif(n = 1:500), nrow = 50, ncol = 10)

## Adds column names with lake and a number separated with a "_"
colnames(A) = paste("lake", 1:10, sep = "_")


#########################################
## Calculating Average using for loop
#########################################


## Creates a matrix to record means in
AloopMeans = matrix(data = 0, nrow = 1, ncol = 10)

## Adds column names with lake and a number separated with a "_"
colnames(AloopMeans) = paste("lake", 1:10, sep = "_")

## for loop to run through each column and calculate the mean.
for(i in 1:ncol(A)){
  
  ## 
  AloopMeans[i] = sum(A[,i])/NROW(A[,i])
}

## Print means generated using the for loop
print(AloopMeans)

####################################
## Using colMeans 
####################################

## Records Average from colMeans
AcolMeans = colMeans(A)

## Prints Averages from colMeans
print(AcolMeans)

```


# Question 2


```{r Q2, echo = TRUE}
## Creates a 3x3x3 array with the values 1 to 27
x = array(1:27, dim = c(3, 3, 3))

## Empty 3x3 array used to record the list of numbers
x.ap = array(,dim = c(3,3))

## For loop to run through the first dimension of x
for(i in 1:dim(x)[1]){
  
  ## For loop for the second dimension of x
  for(q in 1:dim(x)[2]){
    
    ## Resets values in x.char
    x.char = NULL
    
    #For loop for the third dimension of x
    for(u in 1:dim(x)[3]){
      
      ## Records the numbers at position i,q as three characters
      x.char = cbind(x.char,as.character(x[i,q,u]))
    }
    
   ## Combines the list of numbers generated in the for loop above into one string seperated by a comma
   x.ap.list = paste(unlist(x.char), collapse =", ")
   
   ## Record string of numbers into array
   x.ap[i,q] <- x.ap.list
  }
}

## Prints array
print(x.ap)
```

# Question 3

```{r Q3, echo = TRUE}

## How many numbers of the Fibonacci Sequence you want to generate.
fib.length = 30

## Makes a list of 30 elements all set to 0.
Fib.seq = matrix(0, ncol = 1, nrow=fib.length)

## Sets the second term of the matrix to 1.
Fib.seq[2] = 1

## For loop to calcuate sum of previous two values.
for (i in 3:fib.length){
  Fib.seq[i] = Fib.seq[i-1] + Fib.seq[i-2]
  
} # Closes for loop

## Prints out the first 30 terms of the Fibonacci Sequence. 
print(Fib.seq)

```

# Question 4
```{r Q4, echo = TRUE}
## Lists the top 105 songs from the radio station KITS San Francisco on Jan 1, 1992.
top105 = readLines("http://www.textfiles.com/music/ktop100.txt")

## Removes missing no. 54 and 55
top105 = top105[-c(64, 65)]

## Used to filter strings so they just contain the ranking  number preceded by a dot.
y = grep("^[0-9]+([.][0-9])?", top105, value = T)
z = gsub(" .*$", "",  y)

#Prints the ranking number
print(z)
```

# Question 5



```{r Q5, echo = TRUE}

## Removes the period from each number
A = sub("\\D", "",  z)

## Converts the strings to numbers
A = as.numeric(A)

## creates a list that defines any repeated value as True
dup.data = duplicated(A)

## How many ties are present:
print(sum(dup.data))

## for loop to test for repeats and print out what position the tie occurred at.
for(i in 1:length(dup.data)){
  
  ## Tests for any repeated values 
  if(dup.data[i] == TRUE)
    print(A[i]) # Print out repeated positions
  
} # Closes for loop
```

`