---
title: "Homework 5"
author: "Nathaniel Haulk"
date: "10/28/2021"
output: pdf_document
---

```{r packages, echo = TRUE, message = FALSE, warning = FALSE}
library("devtools")

if(!require(neonDivData)) devtools::install_github("daijiang/neonDivData")

library("neonDivData")

library("tidyverse")
```
# Question 1:

```{r Q1, echo = TRUE}

## Pulls the genus for each plant
data_plant$genus = sub(" .*", "", data_plant$taxon_name)

## Selects a random number 100 times between 1 and the length of data_plant
i = sample(1:nrow(data_plant), 100, replace=FALSE)

## Records the genus at the random 
genus_samp = data_plant$genus[i]

## Prints out 100 genus 
print(genus_samp)

```

# Question 2:

```{r Q2, echo = TRUE}

data_plant$taxon_name2 = sub("(\\w\\s\\w+).*", "\\1", data_plant$taxon_name)

## Selects a random number 100 times between 1 and the length of data_plant
i = sample(1:nrow(data_plant), 100, replace=FALSE)

## Records the genus and species name at the random 
taxon2_samp = data_plant$taxon_name2[i]

## Prints out data
print(taxon2_samp)

```

# Question 3

```{r}

## Creates data frame n_1 that counts the number of sample_areas with a size of 1 m2 in data_plant
n_1 = data_plant %>%
  group_by(siteID) %>%
  filter(sample_area_m2 =="1") %>%
  summarise(richness_1m2 = n_distinct(taxon_name2))

## Creates data frame n_10 that counts the number of sample_areas with a size of 1 and 10 m2 in data_plant
n_10 = data_plant %>%
  group_by(siteID) %>%
  filter(sample_area_m2 %in% c("1","10")) %>%
  summarise(richness_10m2 = n_distinct(taxon_name2))

## Creates data frame n_100 that counts the number of sample_areas with a size of 1, 10, and 100 m2 in data_plant
n_100 = data_plant %>%
  group_by(siteID) %>%
  filter(sample_area_m2 %in% c("1","10","100")) %>%
  summarise(richness_100m2 = n_distinct(taxon_name2))

## Joins n_1, n_10, n_100
n_all = left_join(n_1 ,n_10) %>%
  left_join(n_100)

## prints n_all
print(n_all)
```

# Question 4

```{r}

## creates n_all_longer that records site richness based off spatial scale.
n_all_longer = n_all %>%
  pivot_longer(!siteID, names_to = "spatial_scale", values_to = "richness")

## Prints dataframe
print(n_all_longer)
```

# Question 5
```{r}

## Graphs n_all_longer
ggplot(data = n_all_longer, aes(x = spatial_scale, y = richness,  group = siteID))+
  geom_point()+
  geom_line()

```


