---
title: 'Homework #2'
author: "Nathaniel Haulk"
date: "10/07/2021"
output: pdf_document
---

# Question 1
  
## mtcars[mtcars$cyl < 6]
  
|       Missing a comma, should be:  
|       mtcars[mtcars$cyl < 6,]

## mtcars[-1:3,]  
  
|      Needs to be a list so it knows not to include rows 1 to 3:
|      mtcars[-c(1:3),]
  
## mtcars[mtcars$cyl = 8, ]  

|      Needs a second equals sign:  
|      mtcars[mtcars$cyl == 8, ]

## mtcars[mtcars$cyl == 4 | 6, ]  

|      Needs a list of numbers to run through rather than using '|':  
|      mtcars[mtcars$cyl == c(4,6), ]



# Question 2

## x = 1:5  
## x[NA]  

Using the vector X containing the numbers 1 to 5, indexing by NA returns NA 5 times. Since you are indexing by an unknown element, you are instructing R to retrieve  an element it does not have, causing it to print NA.



# Question 3

## mtcars[1:15] vs mtcars[1:15, ]

mtcars[1:15] doesn't work because you are not specifying what rows or columns to pull from. mtcars[1:15,] works because you are denoting you want the first 15 rows to be printed out with all of the columns associated with those rows.


# Question 4

## Line 1: x = matrix(c(1:3, NA, 5:7, NA, NA), nrow = 3)  
## Line 2: x[is.na(x)] = 0  

Line 1 Makes a 3 by 3 matrix (x) with values 1, 2, 3, NA, 5, 6, 7, NA, NA. This means that x[1,2], x[2,3], and x[3,3] all contain NA. Line 2 is used to set all NAs in the matrix into 0. "is.na(x)" detects any NA values and sets them as true. All of the integers are considered false. "x[is.na(x)]" pulls any value marked as true. By setting "x[is.na(x)]" to, any value that is NA is now set to 0.

# Question 5
```{r Question5, echo = TRUE}
## Creates empty row mpg_2 to record what gas efficiency category the car falls under
mtcars['mpg_2'] = NA

## For loop to run through every row of mtcars
for(i in 1:nrow(mtcars)){
  
  ## Tests for low category (mpg < 16)
  if(mtcars[i,1] < 16){
    mtcars[i,12] = "Low"
  } # Closes if loop
  
  ## Tests for Low_intermediate category (16 <= mpg <21)
  else if(mtcars[i,1] < 21){
    mtcars[i,12] = "Low_intermediate"
  } # Closes first else if loop

  ## Tests for Intermediate_high category (21 <= mpg <26)
  else if(mtcars[i,1] < 26){
    mtcars[i,12] = "Intermediate_high"
  } # Closes second else if loop

  ## Sets all other values at high (26 <= mpg)
  else{
    mtcars[i,12] = "High"
  }# Closes else loop
}# Closes for loop


## Used to print out mtcars so mpg and mpg_2 are columns next to each other.
print(mtcars[c(1,12,2:11)])

```

