---
title: "Homework 4"
author: "Nathaniel Haulk"
date: "10/28/2021"
output: pdf_document
---

```{r packages, echo = FALSE, message = FALSE, warning = FALSE}
library('tidyverse')
library('rvest')
```

# Question 1

```{r Q1, echo = TRUE}

## Pulls html data from the schedule and materials page of the course website
sched = read_html("https://introdatasci.dlilab.com/schedule_materials")


## Pulls the schedule data as a table
sched = sched %>% 
  html_elements("table") %>%
  html_table()

## Converts to a data frame for better readability
sched= as.data.frame(sched)
```
# Question 2

```{r Q2, echo = TRUE}

## Removes the day from the date leaving the month
sched$Month = gsub("\\d","",sched[,1])

##  Removes the month from the date leaving the day
sched$Day = gsub("\\D","",sched[,1])

## Prints out schedule in a more readable dataframe containing just the month, day, and topic.
print(sched[c(6,7,2)])

```

# Question 3

```{r Q3, echo = TRUE}
## Counts how many times each month appears
lec.num = sched %>%
  group_by(Month) %>%
  summarise(num = n())

## Sorts the months in decreasing order
lec.num = lec.num[order(lec.num$num, decreasing = TRUE),]

## Prints out how many times each month appears
print(lec.num)

```

# Question 4

```{r}
## Creates a list of all the words
Words = unlist(stringr::str_split(sched$Topic," "))

## removes any punctuation and lowercase letters in the words. 
Words = tolower(sub("[[:punct:]]","",Words))

## Counts the number of times each word appears
t.words = table(Words)

## sorts the number of times each word appears in decreasing order
t.words = sort(t.words, decreasing = TRUE)

## Puts the first 5 words and their frequency into a list
top5 = as.data.frame(t.words[1:5])

## Prints the top 5 results
print(top5)

```

